### ISSUE TITLE
IPFixCol2 unable to translate some IEs

### ISSUE THREAD

**Issue by terminator14** [CESNET/ipfixcol2#26]
I'm using a Mikrotik as my exporter.
It's sending me a template, and data flows.
Most of the data fields are translated by ipfixcol2/libfds without any issues, but there are a few fields which are not. More specifically, the ones I'm seeing that are not translated are:

- postNATSourceIPv4Address (225)
- postNATDestinationIPv4Address (226)
- postNAPTSourceTransportPort (227)
- postNAPTDestinationTransportPort (228)

I'm running ipfixcol2 with the JSON output plugin, and it is giving me these 4 fields as:

- en4294967294:id225: 3339760682
- en4294967294:id226: 167969767
- en4294967294:id227: 5683
- en4294967294:id228: 51769

All 4 IE definitions are in my /usr/etc/libfds/system/elements/iana.xml, so I would think that there should be no problem with them.

I'm using the latest commit of both libfds (dcb27c0ba139d4337bdfc3cc126a7e0454cd1acd) and ipfixcol2 (55155547809fbf6d9bad000ec458b037bec8bb7e).

Am I doing something wrong?

**Comment by Lukas955** [comment]
Hi, this issue has been fixed in `devel` branch of libfds (see #23).

If you don't want to use devel branch, you can just copy [netflow.xml](https://github.com/CESNET/libfds/blob/devel/config/system/elements/netflow.xml) and [netflowExtra.xml](https://github.com/CESNET/libfds/blob/devel/config/system/elements/netflowExtra.xml) to libfds configuration folder - usually `/etc/libfds/system/elements/`.

**Comment by terminator14** [comment]
Confirmed fixed. Copying netflow.xml and netflowExtra.xml to elements dir (in my case /usr/etc/libfds/system/elements/) worked great. Thanks!

On an unrelated note, just because I can't think of a better place to write this, I'd just like to say that this project is easy to setup, use, and works great with both Netflow v9 and IPFIX. It has saved me a ton of work, and I'd like to thank the developers and contributors for their efforts.
